"""
NotionExporter — Exports wiki pages to a Notion database.

Requirements:
  - NOTION_API_KEY environment variable (or passed directly)
  - NOTION_PARENT_PAGE_ID: The Notion page ID to create pages under

Install: pip install notion-client (optional, falls back to raw HTTP)
"""
from __future__ import annotations

import json
import logging
import os
import re
from typing import Dict, Optional

from cli.exporters.base_exporter import BaseExporter, ExportResult

logger = logging.getLogger(__name__)


class NotionExporter(BaseExporter):
    """
    Exports wiki pages to Notion.

    Each wiki page becomes a Notion page under a parent page.
    Markdown is converted to Notion blocks.

    Usage::

        exporter = NotionExporter(api_key="secret_xxx", parent_page_id="abc123")
        result = exporter.export(pages, wiki_title="My Project Wiki")
    """

    NOTION_API_BASE = "https://api.notion.com/v1"
    NOTION_VERSION = "2022-06-28"

    def __init__(
        self,
        api_key: Optional[str] = None,
        parent_page_id: Optional[str] = None,
    ):
        self._api_key = api_key or os.environ.get("NOTION_API_KEY", "")
        self._parent_id = parent_page_id or os.environ.get("NOTION_PARENT_PAGE_ID", "")

    @property
    def name(self) -> str:
        return "notion"

    def export(
        self,
        pages: Dict[str, str],
        wiki_title: str,
        **kwargs,
    ) -> ExportResult:
        """Export all wiki pages to Notion."""
        if not self._api_key:
            return ExportResult(
                success=False,
                exported_count=0,
                target=self.name,
                errors=["NOTION_API_KEY not set. Provide via env or constructor."],
            )
        if not self._parent_id:
            return ExportResult(
                success=False,
                exported_count=0,
                target=self.name,
                errors=["NOTION_PARENT_PAGE_ID not set. Provide via env or constructor."],
            )

        # Create root index page
        root_url = self._create_page(
            title=wiki_title,
            parent_id=self._parent_id,
            content=f"# {wiki_title}\n\nGenerated by RepoLume.",
        )

        root_page_id = self._extract_page_id(root_url) if root_url else self._parent_id

        exported = 0
        errors = []
        urls = [root_url] if root_url else []

        for page_id, content in pages.items():
            if page_id.startswith("__") and page_id.endswith("__"):
                # Business analysis sections — use special titles
                title_map = {
                    "__business_overview__": f"{wiki_title} — Business Overview",
                    "__business_dataflow__": f"{wiki_title} — Data Flow Analysis",
                    "__business_workflow__": f"{wiki_title} — Business Workflows",
                    "__business_impact__": f"{wiki_title} — Impact Analysis",
                }
                title = title_map.get(page_id, page_id)
            else:
                # Extract title from first H1 line
                title = self._extract_title(content, fallback=page_id)

            try:
                url = self._create_page(
                    title=title,
                    parent_id=root_page_id,
                    content=self._clean_markdown(content),
                )
                if url:
                    urls.append(url)
                    exported += 1
                else:
                    errors.append(f"Failed to create Notion page: {page_id}")
            except Exception as e:
                errors.append(f"Error exporting {page_id}: {e}")
                logger.error(f"Notion export error for {page_id}: {e}")

        return ExportResult(
            success=exported > 0,
            exported_count=exported,
            target=self.name,
            errors=errors,
            urls=urls,
        )

    def _create_page(
        self, title: str, parent_id: str, content: str
    ) -> Optional[str]:
        """Create a Notion page and return its URL."""
        import urllib.request

        blocks = self._markdown_to_blocks(content)

        payload = {
            "parent": {"page_id": parent_id},
            "properties": {
                "title": {
                    "title": [{"type": "text", "text": {"content": title[:2000]}}]
                }
            },
            "children": blocks[:100],  # Notion API max 100 blocks per request
        }

        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            f"{self.NOTION_API_BASE}/pages",
            data=data,
            headers={
                "Authorization": f"Bearer {self._api_key}",
                "Content-Type": "application/json",
                "Notion-Version": self.NOTION_VERSION,
            },
            method="POST",
        )

        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                result = json.loads(resp.read())
                return result.get("url", "")
        except Exception as e:
            logger.error(f"Notion API error: {e}")
            return None

    def _markdown_to_blocks(self, md: str) -> list:
        """Convert markdown to Notion block objects (simplified)."""
        blocks = []
        lines = md.split("\n")
        i = 0

        while i < len(lines):
            line = lines[i]

            # Headings
            if line.startswith("### "):
                blocks.append({
                    "object": "block", "type": "heading_3",
                    "heading_3": {"rich_text": [{"type": "text", "text": {"content": line[4:][:2000]}}]}
                })
            elif line.startswith("## "):
                blocks.append({
                    "object": "block", "type": "heading_2",
                    "heading_2": {"rich_text": [{"type": "text", "text": {"content": line[3:][:2000]}}]}
                })
            elif line.startswith("# "):
                blocks.append({
                    "object": "block", "type": "heading_1",
                    "heading_1": {"rich_text": [{"type": "text", "text": {"content": line[2:][:2000]}}]}
                })
            # Code blocks
            elif line.startswith("```"):
                code_lines = []
                lang = line[3:].strip() or "plain text"
                i += 1
                while i < len(lines) and not lines[i].startswith("```"):
                    code_lines.append(lines[i])
                    i += 1
                blocks.append({
                    "object": "block", "type": "code",
                    "code": {
                        "rich_text": [{"type": "text", "text": {"content": "\n".join(code_lines)[:2000]}}],
                        "language": lang[:100],
                    }
                })
            # Bullet list items
            elif line.startswith("- ") or line.startswith("* "):
                blocks.append({
                    "object": "block", "type": "bulleted_list_item",
                    "bulleted_list_item": {
                        "rich_text": [{"type": "text", "text": {"content": line[2:][:2000]}}]
                    }
                })
            # Numbered list items
            elif re.match(r"^\d+\. ", line):
                text = re.sub(r"^\d+\. ", "", line)
                blocks.append({
                    "object": "block", "type": "numbered_list_item",
                    "numbered_list_item": {
                        "rich_text": [{"type": "text", "text": {"content": text[:2000]}}]
                    }
                })
            # Divider
            elif line.strip() in ("---", "***", "___"):
                blocks.append({"object": "block", "type": "divider", "divider": {}})
            # Paragraph (non-empty)
            elif line.strip():
                blocks.append({
                    "object": "block", "type": "paragraph",
                    "paragraph": {
                        "rich_text": [{"type": "text", "text": {"content": line[:2000]}}]
                    }
                })
            i += 1

        return blocks

    def _extract_title(self, content: str, fallback: str = "Page") -> str:
        """Extract H1 title from markdown content."""
        for line in content.split("\n"):
            if line.startswith("# "):
                return line[2:].strip()[:255]
        return fallback[:255]

    def _extract_page_id(self, url: str) -> str:
        """Extract Notion page ID from URL."""
        if not url:
            return self._parent_id
        # URL format: https://notion.so/Title-abc123def456
        parts = url.rstrip("/").split("-")
        if parts:
            raw_id = parts[-1]
            if len(raw_id) == 32:
                return f"{raw_id[:8]}-{raw_id[8:12]}-{raw_id[12:16]}-{raw_id[16:20]}-{raw_id[20:]}"
            return raw_id
        return self._parent_id
